enum Step {
  SEARCH_WITH_CAMERA,
  SEARCH_WITH_CAMERA_BASIC_FORM,
  SEARCH_WITH_CAMERA_ADDITIONAL_FORM,
  SEARCH_WITH_CODE,
  SEARCH_WITH_CODE_BASIC_FORM,
  SEARCH_WITH_CODE_ADDITIONAL_FORM,
  SELF_BASIC_FORM,
  SELF_ADDITIONAL_FORM,
}

const DONE = '';

export { DONE, Step };
