spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cocodi?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: 'root'
    password: 'ssafy'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true